### PR TITLE
Function/api calling dk

### PR DESCRIPTION
**Pull request by deepakMc**

### CODE REVIEW

**Review by chrissloey — CHANGES_REQUESTED** [review]
Looks good, just one thing - could you fix the .gitignore file we created so that it properly ignores src/config/local.js (sorry!) and remove that file from git so that the token isn't in the repo?

**Comment by deepakMc** [comment]
src/config/local.js is added into .gitignore

**Comment by deepakMc** [comment]
src/config/local.js is added into .gitignore

**Comment by chrissloey** [comment]
Great, thanks! 👍

**Pull request merged**
